version: "3.8"
services:
  paste:
    container_name: ghostbin
    build:
      context: .
      args:
          - BRANCH=menudocs
          - COMMIT=unknown
    volumes:
      - spectre:/spectre/storage
    ports:
      - "7000:8080"
    environment:
        SPECTRE_ENV: production
        SPECTRE_BRAND: MenuDocs
    network_mode: "bridge"
volumes:
    spectre:
