name: Publish Docker Image
on:
    push:
        branches: [ menudocs ]
jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Push oengusdotdev to GitHub Packages
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile
                    pull: true
                    push: true
                    build-args: |
                        BRANCH=${{ github.head_ref }}
                        COMMIT=${{ github.sha }}
                    tags: menudocs/spectre:latest
